export * from "./Authentication";
export { default as ErrorPage } from "./404Page";
export { default as Home } from "./Home";
export { default as Services } from "./Services";
export { default as ContactUs } from "./ContactUs";
export { default as Profile } from "./UserProfile";
export { default as WasteDisposal } from "./WasteDisposal";
export { default as WasteRecycling } from "./WasteRecycling";
export { default as ScheduleHistory } from "./ScheduleHistory";
export { default as Checkout } from "./Checkout";
